-- Baseline schema for Phase 1: application users and the central Memory entity.
--
-- Conventions used across all migrations:
--   * UUID primary keys, generated by the application.
--   * timestamptz for every point in time; the application works in UTC.
--   * Enum-like columns are varchar without a CHECK constraint, so new memory types and sources
--     can ship without a migration.

CREATE TABLE users (
    id            UUID         PRIMARY KEY,
    email         VARCHAR(320) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Emails are normalised to lower case by the application; the functional index makes the
-- uniqueness guarantee hold even if some other writer forgets to normalise.
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

CREATE TABLE memories (
    id                UUID         PRIMARY KEY,
    user_id           UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type              VARCHAR(32)  NOT NULL,
    source            VARCHAR(32)  NOT NULL,
    title             VARCHAR(255),
    description       TEXT,
    content           TEXT,
    occurred_at       TIMESTAMPTZ  NOT NULL,
    processing_status VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Primary access pattern: one user's timeline, newest first.
CREATE INDEX ix_memories_user_occurred_at ON memories (user_id, occurred_at DESC);

-- Supports filtering the timeline by memory type.
CREATE INDEX ix_memories_user_type_occurred_at ON memories (user_id, type, occurred_at DESC);

-- Lets the async processor find outstanding work without scanning finished memories.
CREATE INDEX ix_memories_pending_processing ON memories (processing_status, created_at)
    WHERE processing_status IN ('PENDING', 'PROCESSING', 'FAILED');
